SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `duey_packages`;
CREATE TABLE `duey_packages` (
  `id` int(10) UNSIGNED NOT NULL,
  `receiver_id` int(10) UNSIGNED NOT NULL,
  `sender_name` varchar(20) NOT NULL,
  `mesos` int(10) UNSIGNED NOT NULL,
  `message` varchar(50) DEFAULT NULL,
  `type` tinyint(1) UNSIGNED DEFAULT NULL,
  `expired_at` datetime(3) NOT NULL,
  `received_at` datetime(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=big5;


ALTER TABLE `duey_packages`
  ADD PRIMARY KEY (`id`),
  ADD KEY `receiver_id_received_at` (`receiver_id`,`received_at`) USING BTREE;


ALTER TABLE `duey_packages`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
